// ─────────────────────────────────────────────────────────────
// All editable portfolio content lives here. Swap placeholders
// for real data without touching component/animation code.
// ─────────────────────────────────────────────────────────────

export const owner = {
  name: "Kawsar Ahmad",
  roles: [
    "Professional WordPress Developer",
    "Professional Shopify Developer",
    "Website SEO Expert",
    "YouTube SEO Expert",
  ],
  email: "kahmad9966@gmail.com",
  phones: ["+8801975340495", "+8801326852099"],
  whatsapp: "+8801975340495",
  telegram: "https://t.me/kawsar_ahmad_999",
  facebook: "https://www.facebook.com/mhmdkwthr.ahmd.177996",
  linkedin: "https://www.linkedin.com/in/kawser-miah-91928234b/",
};

export const aboutParagraphs = [
  "I build and optimize websites that businesses actually rely on — from WordPress builds that stay fast and maintainable, to Shopify stores tuned for conversion, to search visibility that compounds over time.",
  "My process stays disciplined: clear requirements, clean architecture, and constant communication, so there are no surprises between a kickoff call and a live launch.",
  "Beyond delivery, I stay involved — monitoring performance, fixing issues quickly, and keeping every project healthy long after handoff.",
];

export type Skill = {
  id: string;
  title: string;
  overview: string;
  level: string;
  projects: number;
  services: string[];
  strengths: string[];
};

export const skills: Skill[] = [
  {
    id: "wordpress",
    title: "WordPress Development",
    overview:
      "Custom themes, plugin architecture, and CMS builds engineered for editors and end users alike.",
    level: "Expert · 2+ years",
    projects: 140,
    services: ["Custom theme builds", "Plugin development", "CMS structuring"],
    strengths: ["Clean PHP", "Editor-friendly UX", "Long-term maintainability"],
  },
  {
    id: "elementor",
    title: "Elementor Website Design",
    overview:
      "Pixel-accurate, fast-loading pages built with Elementor for teams who need to self-edit content.",
    level: "Expert · 2+ years",
    projects: 110,
    services: ["Landing pages", "Global style systems", "Widget customization"],
    strengths: ["Design fidelity", "Speed-conscious builds", "Reusable templates"],
  },
  {
    id: "woocommerce",
    title: "WooCommerce",
    overview:
      "End-to-end WooCommerce stores — catalog structure, payments, shipping logic, and checkout optimization.",
    level: "Advanced · 2+ years",
    projects: 65,
    services: ["Store setup", "Payment gateways", "Checkout optimization"],
    strengths: ["Conversion-focused UX", "Inventory logic", "Secure payments"],
  },
  {
    id: "shopify",
    title: "Shopify Store Development",
    overview:
      "Custom Shopify themes and app integrations built to convert and scale with inventory growth.",
    level: "Expert · 2+ years",
    projects: 90,
    services: ["Custom themes", "App integration", "Store migration"],
    strengths: ["Liquid templating", "Conversion design", "Fast storefronts"],
  },
  {
    id: "website-seo",
    title: "Website SEO",
    overview:
      "Technical and on-page SEO that raises organic visibility without compromising design or speed.",
    level: "Expert · 2+ years",
    projects: 200,
    services: ["Technical audits", "On-page optimization", "Keyword strategy"],
    strengths: ["Core Web Vitals", "Structured data", "Content strategy"],
  },
  {
    id: "youtube-seo",
    title: "YouTube SEO",
    overview:
      "Channel and video optimization strategy that improves discoverability and watch-time retention.",
    level: "Advanced · 2+ years",
    projects: 75,
    services: ["Video metadata", "Channel structure", "Growth strategy"],
    strengths: ["Search intent mapping", "Retention tactics", "Analytics-driven"],
  },
  {
    id: "speed",
    title: "Website Speed Optimization",
    overview:
      "Diagnosing and eliminating performance bottlenecks for consistently fast Core Web Vitals.",
    level: "Expert · 2+ years",
    projects: 130,
    services: ["Performance audits", "Asset optimization", "Caching strategy"],
    strengths: ["Lighthouse tuning", "Image pipelines", "Render-blocking fixes"],
  },
  {
    id: "responsive",
    title: "Responsive Website Design",
    overview:
      "Interfaces that hold their design integrity from ultrawide monitors down to small phones.",
    level: "Expert · 2+ years",
    projects: 150,
    services: ["Mobile-first builds", "Cross-device QA", "Adaptive layouts"],
    strengths: ["Fluid grids", "Touch-first interaction", "Device testing"],
  },
  {
    id: "ecommerce",
    title: "E-commerce Website Development",
    overview:
      "Full commerce builds across WordPress and Shopify — catalog to checkout, tuned for revenue.",
    level: "Expert · 2+ years",
    projects: 85,
    services: ["Store architecture", "Payment integration", "Conversion tuning"],
    strengths: ["Funnel thinking", "Platform-agnostic", "Scalable structure"],
  },
  {
    id: "maintenance",
    title: "Bug Fixing & Maintenance",
    overview:
      "Fast, precise fixes for broken sites — from plugin conflicts to critical checkout failures.",
    level: "Expert · 2+ years",
    projects: 300,
    services: ["Emergency fixes", "Version upgrades", "Security patching"],
    strengths: ["Root-cause debugging", "Fast turnaround", "Clear reporting"],
  },
  {
    id: "migration",
    title: "Website Migration",
    overview:
      "Zero-downtime migrations between hosts, platforms, and domains with SEO equity preserved.",
    level: "Advanced · 2+ years",
    projects: 60,
    services: ["Host migration", "Platform migration", "Domain transitions"],
    strengths: ["Redirect mapping", "Data integrity", "SEO preservation"],
  },
  {
    id: "landing",
    title: "Landing Page Design",
    overview:
      "Focused, high-conversion landing pages built around a single clear call to action.",
    level: "Expert · 2+ years",
    projects: 120,
    services: ["Campaign pages", "A/B test variants", "Copy-led layout"],
    strengths: ["Conversion copywriting", "Fast load times", "Clear hierarchy"],
  },
  {
    id: "support",
    title: "Technical Support",
    overview:
      "Ongoing, responsive support so client websites never sit broken for long.",
    level: "Expert · 2+ years",
    projects: 250,
    services: ["Priority support", "Monitoring", "Incident response"],
    strengths: ["Fast response time", "Clear communication", "Proactive fixes"],
  },
  {
    id: "performance",
    title: "Performance Optimization",
    overview:
      "System-level tuning across hosting, caching, and code to keep sites consistently fast.",
    level: "Expert · 2+ years",
    projects: 130,
    services: ["Server tuning", "Caching layers", "Code-level profiling"],
    strengths: ["Holistic diagnostics", "Measurable results", "Stability"],
  },
  {
    id: "communication",
    title: "Client Communication",
    overview:
      "Clear, proactive updates that keep every project predictable from kickoff to delivery.",
    level: "Expert",
    projects: 400,
    services: ["Project scoping", "Status reporting", "Post-launch support"],
    strengths: ["Transparency", "Responsiveness", "Expectation setting"],
  },
];

export const workflowSteps = [
  { id: "01", title: "Requirement Discussion", desc: "Understanding goals, scope, and constraints before anything is designed." },
  { id: "02", title: "Research & Planning", desc: "Mapping the technical approach, timeline, and success metrics." },
  { id: "03", title: "UI / UX Design", desc: "Structuring layout and interaction around real user behavior." },
  { id: "04", title: "Development", desc: "Building with clean, maintainable, production-grade code." },
  { id: "05", title: "Testing & Optimization", desc: "Cross-device QA, performance tuning, and edge-case handling." },
  { id: "06", title: "Project Delivery", desc: "Launch, documentation handoff, and walkthrough." },
  { id: "07", title: "Support & Maintenance", desc: "Ongoing monitoring and fast response after launch." },
];

export const experiences = [
  { id: "wp-dev", title: "WordPress Development", years: "2+ Years", detail: "140+ custom builds across agencies, startups, and direct clients." },
  { id: "shopify-dev", title: "Shopify Development", years: "2+ Years", detail: "90+ storefronts launched with custom theming and app integration." },
  { id: "seo", title: "Website SEO", years: "2+ Years", detail: "200+ sites optimized for organic search visibility." },
  { id: "yt-seo", title: "YouTube SEO", years: "2+ Years", detail: "75+ channels optimized for discoverability and retention." },
  { id: "ecom", title: "E-commerce Development", years: "2+ Years", detail: "85+ full commerce builds from catalog to checkout." },
  { id: "speed", title: "Website Speed Optimization", years: "2+ Years", detail: "130+ sites tuned for Core Web Vitals and load time." },
  { id: "responsive", title: "Responsive Website Design", years: "2+ Years", detail: "150+ layouts built mobile-first and device-tested." },
  { id: "maintenance", title: "Website Maintenance", years: "2+ Years", detail: "300+ fixes delivered with fast turnaround." },
  { id: "consult", title: "Technical Consultation", years: "2+ Years", detail: "Ongoing advisory for teams scaling their web presence." },
];

export type Project = {
  id: string;
  number?: string;
  category: "wordpress" | "shopify";
  title: string;
  description: string;
  services: string[];
  tech: string[];
  image: string;
  liveUrl: string;
  overview: string;
  challenges: string;
  solutions: string;
  features: string[];
};

export const projects: Project[] = [
  {
    id: "istanbul-medical-connect",
    number: " ",
    category: "wordpress",
    title: "Istanbul Medical Connect",
    description: "A trust-building medical tourism site connecting Australian patients with Istanbul healthcare providers.",
    services: ["Custom Design", "SEO", "Lead Generation"],
    tech: ["WordPress", "Elementor"],
    image: "/project9.jpg",
    liveUrl: "#",
    overview: "A premium, trust-focused landing experience guiding international patients through consultation to recovery.",
    challenges: "Medical tourism requires exceptional trust signals to convert hesitant international visitors.",
    solutions: "Built an editorial, reassuring design with clear consultation CTAs and a guided process narrative.",
    features: ["Free consultation flow", "Trust-first editorial design", "Mobile-optimized booking CTA"],
  },
  {
    id: "high-altitude-partners",
    number: " ",
    category: "wordpress",
    title: "High Altitude Partners",
    description: "A retained executive search firm's site built around transparency, flat fees, and measurable results.",
    services: ["Custom Design", "SEO", "Conversion Design"],
    tech: ["WordPress", "Elementor"],
    image: "/project1.jpg",
    liveUrl: "#",
    overview: "A bold, confident recruiting site designed to differentiate on pricing transparency.",
    challenges: "Executive search is a crowded market where firms struggle to communicate pricing clearly.",
    solutions: "Led with fixed-fee messaging and hard proof points (95%+ re-engagement, 98% retention) above the fold.",
    features: ["Stat-driven hero section", "Dual-audience CTAs", "Custom client portal messaging"],
  },
  {
    id: "a-consulting",
    number: " ",
    category: "wordpress",
    title: "A | Consulting",
    description: "A consulting, coaching, and communications firm's site built to establish authority and drive quote requests.",
    services: ["Custom Design", "Copywriting Support", "SEO"],
    tech: ["WordPress", "Elementor"],
    image: "/project2.jpg",
    liveUrl: "#",
    overview: "A polished, dark-themed site positioning the firm as a strategic, high-trust partner.",
    challenges: "The firm offered three distinct services that needed to feel unified, not scattered.",
    solutions: "Organized the offering around four clear pillars with consistent iconography and messaging.",
    features: ["Four-pillar service framework", "Get-a-quote CTA in header", "Editorial photography treatment"],
  },
  {
    id: "imagic-medical",
    number: " ",
    category: "wordpress",
    title: "iMagic Medical",
    description: "A healthcare software product site simplifying how hospitals manage and secure medical imaging data.",
    services: ["Product Site Design", "SEO", "Demo Funnel"],
    tech: ["WordPress", "Custom Theme"],
    image: "/project3.jpg",
    liveUrl: "#",
    overview: "A clean, clinical product site built to drive demo requests from hospital decision-makers.",
    challenges: "Enterprise healthcare buyers needed to quickly grasp compliance and security guarantees.",
    solutions: "Used a clear four-benefit grid (centralized, secure, time-saving, insight-driving) directly below the fold.",
    features: ["Product demo CTA", "Compliance-forward messaging", "Clean clinical visual language"],
  },
  {
    id: "servepoint-capital",
    number: " ",
    category: "wordpress",
    title: "ServePoint Capital",
    description: "A strategic investment advisory site built to convey long-term discipline and quiet confidence.",
    services: ["Custom Design", "SEO", "Brand Positioning"],
    tech: ["WordPress", "Elementor"],
    image: "/project4.jpg",
    liveUrl: "#",
    overview: "A refined, editorial investment site designed to attract long-term capital partners.",
    challenges: "Financial advisory sites often feel generic or overly corporate, undermining trust.",
    solutions: "Used deep navy tones, serif typography, and architectural photography to signal permanence and rigor.",
    features: ["Four-pillar investment philosophy", "Dual CTA strategy", "Editorial typography system"],
  },
  {
    id: "imad-yousef-group",
    number: " ",
    category: "wordpress",
    title: "Imad Yousef Group",
    description: "A UAE and Saudi Arabia-based industrial equipment provider's site built around safety and reliability.",
    services: ["Custom Design", "SEO", "Lead Generation"],
    tech: ["WordPress", "Elementor"],
    image: "/project5.jpg",
    liveUrl: "#",
    overview: "A confident industrial site for a cradle rental and glass lifting equipment provider.",
    challenges: "Industrial B2B buyers needed fast proof of safety standards and equipment reliability.",
    solutions: "Led with real equipment-in-use photography and a four-point trust grid immediately below the fold.",
    features: ["Safety-first messaging", "Direct contact CTA", "Real equipment photography"],
  },
  {
    id: "hikari-kitchen",
    number: " ",
    category: "wordpress",
    title: "Hikari Kitchen",
    description: "A Miami-based Japanese restaurant's site blending traditional aesthetics with modern online ordering.",
    services: ["Custom Design", "Online Ordering Integration", "SEO"],
    tech: ["WordPress", "WooCommerce"],
    image: "/project6.jpg",
    liveUrl: "#",
    overview: "A moody, elegant restaurant site designed to drive both dine-in interest and online orders.",
    challenges: "The restaurant needed to feel premium while keeping ordering friction-free.",
    solutions: "Paired dark, atmospheric food photography with clear dual CTAs for menu browsing and ordering.",
    features: ["Explore menu + order now CTAs", "Premium dark aesthetic", "Local SEO for Miami dining searches"],
  },
   {
    id: "black-shado",
    number: " ",
    category: "wordpress",
    title: "Black Shadô",
    description: "A dual-audience luxury perfume brand website split cleanly between feminine and masculine lines.",
    services: ["Custom Design", "Brand Design", "Multilingual Setup"],
    tech: ["WordPress", "Elementor"],
    image: "/project8.jpg",
    liveUrl: "#",
    overview: "A high-contrast luxury fragrance website split into two distinct product lines.",
    challenges: "Two very different audiences (feminine and masculine fragrance lines) needed equal visual weight.",
    solutions: "Used a symmetrical split-screen layout with matching CTA structure for both product lines.",
    features: ["Split dual-audience layout", "French-language luxury copy", "Consistent scent-line branding"],
  },
    {
    id: "relyfes",
    number: " ",
    category: "wordpress",
    title: "Relyfes",
    description: "A multi-category online marketplace connecting buyers and sellers across electronics, furniture, and more.",
    services: ["Custom Development", "Marketplace Features", "SEO"],
    tech: ["WordPress", "Custom Theme"],
    image: "/project14.png",
    liveUrl: "#",
    overview: "A classifieds-style marketplace site built to help people find listings quickly by category and location.",
    challenges: "The platform needed fast, location-aware search across many unrelated product categories.",
    solutions: "Built a unified search bar with location filtering and a clean category-grid homepage.",
    features: ["Location-based search", "Category browsing grid", "Post-a-listing flow"],
  },
  {
    id: "king-jesus-universal-ministry",
    number: " ",
    category: "wordpress",
    title: "King Jesus Universal Ministry",
    description: "A church website built to welcome visitors, share service times, and encourage community engagement.",
    services: ["Custom Design", "Donation Integration", "SEO"],
    tech: ["WordPress", "Elementor"],
    image: "/project15.png",
    liveUrl: "#",
    overview: "A warm, inviting ministry site designed to draw visitors in and make giving simple.",
    challenges: "The ministry needed a prominent, trustworthy way to accept online donations.",
    solutions: "Placed a clear donate CTA in the header and paired it with authentic worship photography.",
    features: ["Prominent donate CTA", "Service info bar", "Location and contact details"],
  },
  {
    id: "goliath-publishing-network",
    number: " ",
    category: "wordpress",
    title: "Goliath Publishing Network",
    description: "A B2B site for a board game publisher connecting international partners for game localization.",
    services: ["Custom Design", "SEO", "Partner Outreach"],
    tech: ["WordPress", "Elementor"],
    image: "/project16.png",
    liveUrl: "#",
    overview: "A globally-minded B2B site built to attract international publishing partners.",
    challenges: "The brand needed to visually communicate global reach and partnership opportunity.",
    solutions: "Used a world map with connection lines and a direct partner-with-us CTA above the fold.",
    features: ["Global network visualization", "Partner outreach CTA", "Playful brand-consistent icons"],
  },
  {
    id: "promise-venue-wholesale",
    number: " ",
    category: "wordpress",
    title: "Promise Venue Wholesale LLC",
    description: "A B2B wholesale distribution site for stationery, gardening equipment, and general merchandise.",
    services: ["Custom Design", "SEO", "Lead Generation"],
    tech: ["WordPress", "Elementor"],
    image: "/project17.png",
    liveUrl: "#",
    overview: "A straightforward, trust-focused site for a wholesale distributor serving North American retailers.",
    challenges: "B2B buyers needed to quickly understand product categories and how to get in touch.",
    solutions: "Led with real warehouse photography and a single clear contact CTA above the fold.",
    features: ["Real warehouse photography", "Clear contact CTA", "Product category messaging"],
  },
  {
    id: "bluestar-electrical",
    number: " ",
    category: "wordpress",
    title: "Bluestar Electrical LLC",
    description: "A local electrician service site built to drive service requests across Southern New Hampshire.",
    services: ["Custom Design", "Local SEO", "Lead Generation"],
    tech: ["WordPress", "Elementor"],
    image: "/project18.png",
    liveUrl: "#",
    overview: "A trust-driven local service site designed to convert visitors into service requests and calls.",
    challenges: "Local service businesses need fast trust-building and an obvious way to call or request service.",
    solutions: "Paired a direct phone number button with a real technician photo and a clear service area headline.",
    features: ["Click-to-call button", "Service area headline", "Real technician photography"],
  },


    {
    id: "mediaone-seo-geo",
    number: " ",
    category: "wordpress",
    title: "MediaOne — SEO & GEO",
    description: "A Singapore marketing agency site built around SEO and AI-search (GEO) visibility.",
    services: ["Custom Design", "SEO", "Lead Generation"],
    tech: ["WordPress", "Elementor"],
    image: "/project19.png",
    liveUrl: "#",
    overview: "A confident agency site that pairs strong proof points with a clear free-audit offer.",
    challenges: "The agency had to explain a new service (GEO) alongside traditional SEO without confusing visitors.",
    solutions: "Led with a stats bar and a four-pillar trust section, with a free audit CTA in the hero.",
    features: ["Stats-driven hero", "Free SEO & GEO audit CTA", "Four-pillar trust section"],
  },
  {
    id: "mediaone-paid-media",
    number: " ",
    category: "wordpress",
    title: "MediaOne — Paid Media",
    description: "A performance marketing page showcasing lead pipeline results and low-commitment engagement terms.",
    services: ["Custom Design", "Conversion Design", "SEO"],
    tech: ["WordPress", "Elementor"],
    image: "/project20.png",
    liveUrl: "#",
    overview: "A clean, data-forward landing page for a paid media service with a live-campaign dashboard visual.",
    challenges: "Prospects needed quick proof of results and reassurance about commitment before enquiring.",
    solutions: "Added a campaign metrics card and clear reassurance points (no long contracts, 30-day pilots).",
    features: ["Campaign metrics card", "Dual CTAs", "Click-to-call in header"],
  },
  {
    id: "the-subpoena-service",
    number: " ",
    category: "wordpress",
    title: "The Subpoena Service, Inc.",
    description: "A professional legal support website for subpoena preparation, service, and production in California.",
    services: ["Custom Design", "Local SEO", "Lead Generation"],
    tech: ["WordPress", "Custom Theme"],
    image: "/project21.png",
    liveUrl: "#",
    overview: "A restrained, editorial site that signals reliability and confidentiality to law firms.",
    challenges: "Legal buyers expect a serious, trustworthy tone and an obvious way to start a service request.",
    solutions: "Used serif typography, a neutral palette, and a four-step process layout with a prominent phone CTA.",
    features: ["Four-step process section", "Click-to-call CTA", "Professional serif design"],
  },
  {
    id: "rainfactory",
    number: " ",
    category: "wordpress",
    title: "Rainfactory",
    description: "An irrigation products store for garden owners, landscapers, and farmers, with a multilingual setup.",
    services: ["WooCommerce Development", "Multilingual Setup", "SEO"],
    tech: ["WordPress", "WooCommerce"],
    image: "/project22.png",
    liveUrl: "#",
    overview: "A fresh, nature-led ecommerce site for a curated range of irrigation technology.",
    challenges: "A technical product range had to feel approachable for home gardeners and professionals alike.",
    solutions: "Paired lifestyle photography with clear navigation, manuals and guides, and a language switcher.",
    features: ["Product catalog", "Manuals & guides section", "Language switcher"],
  },
  {
    id: "nord-ejendomsservice",
    number: " ",
    category: "wordpress",
    title: "NORD Ejendomsservice",
    description: "A Danish property service company site serving housing associations and commercial properties.",
    services: ["Custom Design", "Local SEO", "Lead Generation"],
    tech: ["WordPress", "Elementor"],
    image: "/project23.png",
    liveUrl: "#",
    overview: "A bold, Danish-language site built to win quotes from property managers across Zealand.",
    challenges: "Property managers wanted proof of reliability and a fast, obvious way to request a quote.",
    solutions: "Highlighted four trust stats, a quote CTA in the header and hero, and a visible phone number.",
    features: ["Danish-language content", "Request-a-quote CTA", "Trust statistics grid"],
  },
  {
    id: "safari-tailor-made-experiences",
    number: " ",
    category: "wordpress",
    title: "Safari — Tailor-Made Experiences",
    description: "A luxury travel brand site offering bespoke journeys in Morocco.",
    services: ["Custom Design", "Brand Design", "SEO"],
    tech: ["WordPress", "Elementor"],
    image: "/project24.png",
    liveUrl: "#",
    overview: "An immersive, destination-led site that sells the experience before the itinerary.",
    challenges: "A premium travel brand had to feel personal and inspiring instead of like a booking engine.",
    solutions: "Used full-bleed destination photography, gold typography, and three clear journey entry points.",
    features: ["Full-bleed hero", "Three journey CTAs", "Social links and language selector"],
  },
  {
    id: "trash-dash",
    number: " ",
    category: "wordpress",
    title: "Trash Dash",
    description: "A family-owned junk removal and valet trash service site for Greater Charlotte.",
    services: ["Custom Design", "Local SEO", "Lead Generation"],
    tech: ["WordPress", "Elementor"],
    image: "/project25.png",
    liveUrl: "#",
    overview: "A friendly, trustworthy local service site aimed at property managers and residents.",
    challenges: "A local business needed to stand out from franchises and make calling effortless.",
    solutions: "Led with a family-owned message, a click-to-call header button, and four value cards.",
    features: ["Click-to-call button", "Four value cards", "Social links in header"],
  },
  {
    id: "rheam-medical",
    number: " ",
    category: "wordpress",
    title: "Rheam Medical",
    description: "A medical device startup site introducing a robotic trocar insertion research platform.",
    services: ["Custom Design", "Content Strategy", "SEO"],
    tech: ["WordPress", "Custom Theme"],
    image: "/project26.png",
    liveUrl: "#",
    overview: "A minimal, clinical site that explains an early-stage research prototype clearly and honestly.",
    challenges: "The site had to convey innovation while being upfront that the product is not for sale.",
    solutions: "Used bold typography, a plain-language product summary, and a visible research-prototype notice.",
    features: ["Plain-language product summary", "Research prototype notice", "Contact CTA"],
  },

    {
    id: "feriehjem",
    number: " ",
    category: "wordpress",
    title: "FerieHjem",
    description: "A Danish vacation-home rental management site offering a transparent, flat-rate service.",
    services: ["Custom Design", "Conversion Design", "SEO"],
    tech: ["WordPress", "Elementor"],
    image: "/project27.png",
    liveUrl: "#",
    overview: "A trust-driven site helping Danish summer-house owners estimate rental income and get started quickly.",
    challenges: "Owners needed a fast, transparent way to see what they'd actually earn compared to typical agencies.",
    solutions: "Built an interactive earnings calculator comparing FerieHjem's flat 17.5% rate against a typical 30% agency cut.",
    features: ["Interactive earnings calculator", "Fee comparison bar chart", "Dual booking/consultation CTAs"],
  },

    // ───────────── Shopify projects start here ─────────────
  
    {
    id: "ember-and-lore",
    number: " ",
    category: "shopify",
    title: "Ember & Lore",
    description: "A hand-poured candle and coffee brand storefront built for an intimate, ritual-driven shopping experience.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project10.jpg",
    liveUrl: "#",
    overview: "A moody, sensory-driven Shopify storefront for a small-batch candle and coffee brand.",
    challenges: "The brand needed a premium feel without losing the handmade, small-batch authenticity.",
    solutions: "Used warm dark photography and minimal copy to let the product imagery carry the emotional weight.",
    features: ["Dual product-line storefront", "Warm editorial photography", "Simple two-CTA layout"],
  },
  {
    id: "cote-royale",
    number: " ",
    category: "shopify",
    title: "Côte Royale",
    description: "A Mediterranean-inspired home decor brand's storefront built around timeless, artisan craftsmanship.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project7.jpg",
    liveUrl: "#",
    overview: "An editorial-style Shopify storefront for a collectible home decor and textiles brand.",
    challenges: "The brand needed to justify premium pricing through perceived craftsmanship and story.",
    solutions: "Used lifestyle photography and a four-value trust bar to reinforce quality before the shop link.",
    features: ["Lifestyle-led product presentation", "Four-value trust bar", "Discover-the-collection CTA"],
  },
   {
    id: "amoressi",
    number: " ",
    category: "shopify",
    title: "Amoressi",
    description: "A modern jewelry brand storefront built around mix-and-match stacking pieces.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project11.jpg",
    liveUrl: "#",
    overview: "A clean, editorial jewelry storefront designed to make stacking rings and bracelets feel effortless.",
    challenges: "The brand needed a layout that showcased how pieces could be mixed and matched together.",
    solutions: "Used a collage-style hero grid to visually demonstrate stacking combinations in real settings.",
    features: ["Collage-style product hero", "Category mega-menu", "Mobile-first shopping flow"],
  },
  {
    id: "starla-marz",
    number: " ",
    category: "shopify",
    title: "Starla Marz",
    description: "A bohemian jewelry brand storefront built around adventure, spirit, and handcrafted adornments.",
    services: ["Shopify Development", "Brand Design", "Photography Direction"],
    tech: ["Shopify", "Liquid"],
    image: "/project12.jpg",
    liveUrl: "#",
    overview: "An atmospheric, lifestyle-driven storefront designed to capture a free-spirited brand identity.",
    challenges: "The brand's boho identity needed to feel premium rather than casual online.",
    solutions: "Used full-bleed lifestyle photography and elegant serif typography to elevate the aesthetic.",
    features: ["Full-bleed hero photography", "Elegant serif brand typography", "Story-led homepage"],
  },
  {
    id: "jubilore",
    number: " ",
    category: "shopify",
    title: "Jubilore",
    description: "A bible-inspired streetwear brand storefront built around bold graphic storytelling.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project13.jpg",
    liveUrl: "#",
    overview: "A high-contrast streetwear storefront built to let bold graphic artwork carry the brand.",
    challenges: "The brand needed an edgy, gothic aesthetic without sacrificing usability or load speed.",
    solutions: "Used a stark black-and-white palette with a bold display typeface and dual clear CTAs.",
    features: ["Bold gothic typography system", "Dual shop/story CTAs", "High-contrast product photography"],
  },
    {
    id: "social-work-practice-hub",
    number: " ",
    category: "shopify",
    title: "The Social Work Practice Hub",
    description: "A resource storefront offering reflective tools and learning materials for social work professionals.",
    services: ["Shopify Development", "Digital Product Setup", "SEO"],
    tech: ["Shopify", "Liquid"],
    image: "/project28.png",
    liveUrl: "#",
    overview: "A calm, editorial storefront for downloadable social work resources and premium learning tools.",
    challenges: "The store needed to feel professional and evidence-based rather than like a generic resource marketplace.",
    solutions: "Used warm, muted tones and clear dual CTAs separating free resources from premium tools.",
    features: ["Free vs premium resource split", "Clean editorial layout", "Cross-profession positioning"],
  },
  {
    id: "franity",
    number: " ",
    category: "shopify",
    title: "Franity",
    description: "A clean beauty brand storefront for cruelty-free, glow-boosting cosmetics.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project29.png",
    liveUrl: "#",
    overview: "A soft, feminine storefront built to highlight product quality and natural glow.",
    challenges: "The brand needed strong product visibility without overwhelming the lifestyle photography.",
    solutions: "Added a floating product card over the hero image linking straight to the featured product.",
    features: ["Floating product spotlight card", "Soft botanical brand styling", "Direct explore-products CTA"],
  },
  {
    id: "after-the-build",
    number: " ",
    category: "shopify",
    title: "After The Build",
    description: "A pre-launch furniture and home goods store built around a waitlist-driven launch strategy.",
    services: ["Shopify Development", "Waitlist Setup", "Brand Design"],
    tech: ["Shopify", "Liquid"],
    image: "/project30.png",
    liveUrl: "#",
    overview: "A moody, premium storefront designed to build anticipation ahead of a full product launch.",
    challenges: "With no live catalog yet, the site needed to convert visitors into waitlist signups instead of sales.",
    solutions: "Led with striking interior photography and a single, unmissable join-the-waitlist CTA.",
    features: ["Waitlist signup flow", "Search-ready product taxonomy", "Premium interior photography"],
  },
  {
    id: "water-flosser-for-tonsil-stones",
    number: "  ",
    category: "shopify",
    title: "WaterFlosserForTonsilStones.store",
    description: "A niche oral-care storefront for a targeted water flosser designed for gentle tonsil stone care.",
    services: ["Shopify Development", "Conversion Design", "SEO"],
    tech: ["Shopify", "Liquid"],
    image: "/project31.png",
    liveUrl: "#",
    overview: "A trust-focused storefront for a specialized health product with a clear usage guide.",
    challenges: "A sensitive, niche product needed to feel approachable and medically credible, not gimmicky.",
    solutions: "Used plain-language benefit badges and a calm color palette to build confidence before purchase.",
    features: ["Benefit badge row", "Usage guide emphasis", "Clean single-product focus"],
  },
  {
    id: "wilma-copenhagen",
    number: " ",
    category: "shopify",
    title: "Wilma Copenhagen",
    description: "A Danish furniture and home retailer storefront spanning garden, lighting, and interior categories.",
    services: ["Shopify Development", "Multi-category Navigation", "SEO"],
    tech: ["Shopify", "Liquid"],
    image: "/project32.png",
    liveUrl: "#",
    overview: "A large-catalog Danish home retailer site built for easy cross-category browsing.",
    challenges: "A wide product range across many categories risked overwhelming the navigation and homepage.",
    solutions: "Built a clear mega-menu structure with a bold seasonal campaign banner leading into collections.",
    features: ["Multi-category mega menu", "Seasonal campaign banner", "Danish-language storefront"],
  },
  {
    id: "pulse-fix",
    number: " ",
    category: "shopify",
    title: "Pulse Fix",
    description: "A wearable-tech accessory storefront for an optical sensor lens that improves smartwatch heart-rate accuracy.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project33.png",
    liveUrl: "#",
    overview: "A dark, performance-driven storefront for a single-purpose wearable accessory.",
    challenges: "A technical accessory product needed to clearly explain its benefit in just a few seconds.",
    solutions: "Used bold contrast typography and a direct product cutaway image to show exactly how it works.",
    features: ["Product cutaway visual", "Benefit-icon trio", "Swedish-language storefront"],
  },
  {
    id: "brothers-and-friends",
    number: "  ",
    category: "shopify",
    title: "Brothers and Friends",
    description: "An organic cold-pressed juice brand storefront with an immersive video hero.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project34.png",
    liveUrl: "#",
    overview: "A bold, high-energy storefront using motion to sell freshness and quality.",
    challenges: "The brand needed to stand out in a crowded juice market without relying on clichéd fruit shots.",
    solutions: "Used a full-bleed video hero of fruit in motion with strong condensed typography over it.",
    features: ["Full-bleed video hero", "Bold condensed typography", "Single-focus shop-now CTA"],
  },
  {
    id: "yum-ice-creamery",
    number: "  ",
    category: "shopify",
    title: "Yum Ice Creamery & Sweet Shop",
    description: "A storefront for a physical ice creamery and sweet shop, extending the in-store experience online.",
    services: ["Shopify Development", "Brand Design", "Local SEO"],
    tech: ["Shopify", "Liquid"],
    image: "/project35.png",
    liveUrl: "#",
    overview: "A bright, playful storefront that mirrors the charm of the physical storefront online.",
    challenges: "The brand needed the website to feel as inviting and photogenic as the physical shop itself.",
    solutions: "Led with a real storefront photo and organized navigation around shop, gifting, and story.",
    features: ["Real storefront photography", "Corporate gifting section", "Playful brand color system"],
  },
  {
    id: "kindest-regards",
    number: "  ",
    category: "shopify",
    title: "Kindest Regards",
    description: "A sentimental gifting brand storefront centered around a 'forever gifting' keepsake movement.",
    services: ["Shopify Development", "Brand Design", "CRO"],
    tech: ["Shopify", "Liquid"],
    image: "/project36.png",
    liveUrl: "#",
    overview: "An emotionally-led storefront for a keepsake gifting brand built around memory preservation.",
    challenges: "The product concept (QR-linked keepsakes) needed a quick, intuitive visual explanation.",
    solutions: "Used a warm lifestyle photo paired directly with a product shot showing the keepsake and QR code together.",
    features: ["Lifestyle + product pairing", "Carousel-driven homepage", "Warm, sentimental brand tone"],
  },
  {
    id: "dastarkhan",
    number: "  ",
    category: "shopify",
    title: "Dastarkhan",
    description: "A granulated black tea brand storefront celebrating authentic Central Asian tea culture.",
    services: ["Shopify Development", "Brand Design", "SEO"],
    tech: ["Shopify", "Liquid"],
    image: "/project37.png",
    liveUrl: "#",
    overview: "A warm, heritage-driven storefront built to evoke tradition and shared moments around tea.",
    challenges: "A commodity-feeling product (tea) needed strong emotional and cultural differentiation.",
    solutions: "Used authentic tablescape photography and ornamental corner details to signal heritage and quality.",
    features: ["Heritage ornamental design", "Multilingual-ready layout", "Dual shop/story CTAs"],
  },
  {
    id: "terea-blends",
    number: "  ",
    category: "shopify",
    title: "TEREA Blends",
    description: "A multi-region tobacco product storefront organized by country-specific blend collections.",
    services: ["Shopify Development", "Multi-region Navigation", "SEO"],
    tech: ["Shopify", "Liquid"],
    image: "/project38.png",
    liveUrl: "#",
    overview: "A sleek, teal-branded storefront organizing products by origin country for easy discovery.",
    challenges: "A wide range of regional product lines needed clear, scannable navigation without clutter.",
    solutions: "Built a country-based navigation bar so shoppers could jump straight to their preferred regional blend.",
    features: ["Country-based navigation", "New-series product spotlight", "Consistent teal brand system"],
  },
  {
    id: "paulo-pinto",
    number: "  ",
    category: "shopify",
    title: "Paulo Pinto",
    description: "A live vocalist's booking site for weddings, corporate events, and private parties.",
    services: ["Shopify Development", "Media Integration", "Lead Generation"],
    tech: ["Shopify", "Liquid"],
    image: "/project39.png",
    liveUrl: "#",
    overview: "An elegant, media-rich site helping a performer convert visitors into event bookings.",
    challenges: "Prospective clients needed to hear and see performance quality before requesting a quote.",
    solutions: "Embedded video performances directly on the homepage with clear event-type filter buttons.",
    features: ["Embedded video performances", "Event-type quick filters", "Get-a-quote CTA"],
  },
  {
    id: "rock-n-roll-collectibles",
    number: "  ",
    category: "shopify",
    title: "Rock n Roll Collectibles",
    description: "A collectibles storefront offering replica instruments connected to legendary music history.",
    services: ["Shopify Development", "Brand Design", "Content Strategy"],
    tech: ["Shopify", "Liquid"],
    image: "/project40.png",
    liveUrl: "#",
    overview: "A nostalgic, story-driven storefront for music memorabilia and replica instrument collectibles.",
    challenges: "Collectors needed to feel the authenticity and craftsmanship behind each replica piece.",
    solutions: "Used dramatic instrument photography and a running blog to deepen the storytelling around each era.",
    features: ["Dramatic product photography", "Weekly blog integration", "Multi-currency support"],
  },
  {
    id: "fru-lund-and-co",
    number: " ",
    category: "shopify",
    title: "Fru Lund & Co",
    description: "A Danish vintage and home craft storefront spanning décor, wellness, and seasonal collections.",
    services: ["Shopify Development", "Multi-category Navigation", "SEO"],
    tech: ["Shopify", "Liquid"],
    image: "/project41.png",
    liveUrl: "#",
    overview: "A charming, vintage-styled storefront organized around seasonal collections and curated categories.",
    challenges: "A broad vintage and lifestyle catalog needed structure without losing its cozy, curated feel.",
    solutions: "Built a seasonal campaign grid on the homepage backed by a detailed category navigation menu.",
    features: ["Seasonal campaign grid", "In-store pickup messaging", "Danish-language storefront"],
  },
];
export const achievements = [
  { label: "Completed Projects", value: 400, suffix: "+" },
  { label: "Satisfied Clients", value: 350, suffix: "+" },
  { label: "Years of Experience", value: 6, suffix: "+" },
  { label: "Countries Served", value: 24, suffix: "" },
  { label: "Avg. Response Time", value: 2, suffix: "h" },
  { label: "Client Satisfaction", value: 98, suffix: "%" },
  { label: "SEO Campaigns", value: 200, suffix: "+" },
  { label: "Performance Gains", value: 65, suffix: "%" },
];

export type Testimonial = {
  id: string;
  name: string;
  country: string;
  company: string;
  review: string;
  rating: number;
  avatar: string;
};

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah Mitchell",
    country: "United States",
    company: "Aurora Clinic",
    review: "Kawsar rebuilt our site and bookings went up within the first month. Communication was clear the entire way through.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  },
  {
    id: "t2",
    name: "James Whitfield",
    country: "United Kingdom",
    company: "Northwind Realty",
    review: "The migration was seamless — no ranking loss, and the new search is genuinely faster than anything we had before.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
  },
  {
    id: "t3",
    name: "Elena Novak",
    country: "Germany",
    company: "Verdant Goods",
    review: "Our checkout conversion improved noticeably after the rebuild. Kawsar understood exactly what we needed.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200&q=80",
  },
  {
    id: "t4",
    name: "Daniel Reyes",
    country: "Canada",
    company: "Forge Athletics",
    review: "Returns dropped noticeably after the size-fit tool launched. Meticulous work and fast turnaround.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  },
];

export const serviceOptions = [
  "WordPress Development",
  "Shopify Development",
  "Website SEO",
  "YouTube SEO",
  "Website Speed Optimization",
  "Website Maintenance",
  "Bug Fix",
  "Technical Consultation",
  "Other",
] as const;
